name: "Louise's Legacy Project"
favicon: null
layout_spectrum: 0.8819653068203479
typography_spectrum: 0.22421888052485883
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.28360146353952587
  lightness: 0.2826537627261132
  saturation: 0.7333058377262205
  rhythmicContrast: 0.5166899859905243
purpose: []
